name: build & test frontend

on: [push, pull_request]

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Setup node
      uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: lts/*
    - name: install npm deps
      working-directory: ./client
      run: npm install
    - name: build site
      working-directory: ./client
      run: npm run build
    - name: run node tests
      working-directory: ./client
      run: npm test
